### ISSUE TITLE
Chart Disappears

### ISSUE THREAD

**Issue by SturmB** [amcharts/responsive#11]
I am not sure why, but this plugin is making my entire chart disappear except for its legend. Here's what the chart normally looks like:
<img width="1041" alt="screen shot 2018-02-07 at 11 32 33 am" src="https://user-images.githubusercontent.com/6216224/35928325-e7081cd6-0bfa-11e8-81eb-86896e0c9671.png">
And on a mobile display, the legend takes up too much room:
<img width="377" alt="screen shot 2018-02-07 at 11 33 49 am" src="https://user-images.githubusercontent.com/6216224/35928369-fde5c520-0bfa-11e8-9e45-c36f4cc6415b.png">
Thus, the need for this plugin. However, when I enable the responsive plugin, the chart area is blank:
<img width="1046" alt="screen shot 2018-02-07 at 11 33 00 am" src="https://user-images.githubusercontent.com/6216224/35928397-0ea52400-0bfb-11e8-89c7-8f0ddf49af17.png">
And it disappears entirely when viewed on mobile--the legend disappears, as it should on mobile, but the chart is still gone. And both are still gone when I resize the browser window back to desktop-size.

All I can figure is that, because I am creating the graphs at runtime instead of in the JSON object when the chart is first initialized, perhaps `responsive` doesn't have anything to work with when it activates? (i.e., I am not using the `dataProvider` property.) Is there an API call so I can activate it _after_ I've populated the graphs?

**Comment by martynasma** [comment]
That looks weird.

Would you be able to share your complete config and data for the chart, so that we can test?

**Comment by SturmB** [comment]
Absolutely. I should have posted that initially, as well; sorry. You can find [the file where it is initialized](https://github.com/SturmB/sky-schedule/blob/master/resources/assets/js/charts-totals.js) on [my project's repo](https://github.com/SturmB/sky-schedule). I'm sorry the code is a mess; I'm still learning.

**Comment by martynasma** [comment]
No worries.

Any chance of some sample data? Just so we don't have to invent things.

**Comment by SturmB** [comment]
Another excellent point and oversight on my part. Here's the sample set of data as a CSV (renamed to TXT so I could upload it here) that was used to generate those images.
[num_line_items_by_status_between_dates.txt](https://github.com/amcharts/responsive/files/1707805/num_line_items_by_status_between_dates.txt)

**Comment by martynasma** [comment]
Thanks.

I still had to modify heavily to make it work. Here's what I came up with:

https://codepen.io/team/amcharts/pen/fe6cdaa69d4f76b9e180e0c26aa29095?editors=0010

However, I can't reproduce the disappearing effect you mentioned.

Can you modify the example to match your specific setup so that we can reproduce the issue?

**Comment by SturmB** [comment]
Height.

It turns out that the chart `div` _needs_ to have a specific height set. It draws fine using a default value (300px, maybe?) without the responsive plugin. Once the plugin is added and enabled, however, the chart does not draw if it does not have a `height` style on it. Yay, it works now! And the legend disappears as it should!

Interesting side note: Your CodePen may not be loading the responsive plugin or something because the legend does _not_ disappear when the browser width is reduced to a mobile size. Regardless, thank you so much for taking the time to look into this for me!

**Comment by martynasma** [comment]
OK, great. Glad you worked that out!
