### ISSUE TITLE
 pointing his finger on the graph and tells exactly point  

### ISSUE THREAD

**Issue by bb14521** [amcharts/responsive#4]
i have made a graph using the amcharts lib.  

https://github.com/bb14521/amcharts-javascript-graphs

when i point on the curve, it has to show the point at cursor. but it shows points of another curves. 
 why ? how can i fix it.

**Comment by martynasma** [comment]
Can you please reach out directly to amCharts support on contact@amcharts.com?

This does not seems to be related to Responsive plugin in any way. This repo is for the plugin.

Thanks!
